"""Testy súladu migrácií a modelov.

Toto je poistka proti konkrétnej chybe, ktorá sa už raz stala: do modelu
pribudol stĺpec, migrácia sa nedopísala (alebo nespustila), a appka vracala
500 na `UndefinedColumnError` až naživo. `Base.metadata.create_all` v testoch
to nikdy nemohlo zachytiť, pretože schému staval z tých istých modelov.

Schému teraz stavia `alembic upgrade head` (pozri fixture `db_engine`) a
`alembic check` navyše porovná výsledok s modelmi.
"""

import pytest

from tests.conftest import alembic_config, run


def test_models_match_migrations(db_engine):
    """`alembic check` — model a migrácie nesmú driftovať.

    Keď tento test padne, znamená to, že si zmenil model a nedopísal migráciu.
    Vygeneruj ju: `alembic revision --autogenerate -m "..."` a skontroluj ju
    očami, autogenerate nie je neomylný.
    """
    from alembic import command
    from alembic.util.exc import AutogenerateDiffsDetected

    try:
        command.check(alembic_config())
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"Model a migrácie sa rozišli:\n{exc}")


def test_database_is_at_head(db_engine):
    """Testovacia databáza musí byť na najnovšej revízii."""
    from alembic.runtime.migration import MigrationContext
    from alembic.script import ScriptDirectory

    async def current() -> str | None:
        async with db_engine.connect() as conn:
            return await conn.run_sync(
                lambda sync_conn: MigrationContext.configure(sync_conn).get_current_revision()
            )

    head = ScriptDirectory.from_config(alembic_config()).get_current_head()
    assert run(current()) == head


def test_every_migration_can_be_downgraded_and_reapplied(db_engine):
    """Migrácie musia ísť aj dole. Bez toho sa nasadenie nedá vrátiť.

    Ide o jeden krok z head a späť — to je presne to, čo pri odvolaní
    nasadenia potrebuješ, a zároveň to nerozbúra dáta ostatných testov.
    """
    from alembic import command
    from alembic.script import ScriptDirectory

    config = alembic_config()
    script = ScriptDirectory.from_config(config)
    head = script.get_current_head()
    previous = script.get_revision(head).down_revision
    if previous is None:
        pytest.skip("Je len jedna migrácia, nie je kam downgradovať")

    command.downgrade(config, previous)
    command.upgrade(config, "head")
